// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.ScratchMsgs.allPmLocales');

goog.require('Blockly.ScratchMsgs');

Blockly.ScratchMsgs.pmLocales["en"] = {
    "PM_CONTROL_CASE": "case %1 %2",
    "PM_CONTROL_CASE_DEFAULT": "default",
    "PM_CONTROL_CASE_EXIT": "exit case %1",
    "PM_CONTROL_CASE_NEXT": "run next case when %1",
    "PM_CONTROL_CASE_SWITCH": "switch %1 %2",
    "PM_CONTROL_CONTINUELOOP": "continue loop %1",
    "PM_CONTROL_DECRCOUNTER": "decrement counter",
    "PM_CONTROL_DELETECLONESOF": "delete clones of %1",
    "PM_CONTROL_DO": "do %1 %2",
    "PM_CONTROL_ESCAPELOOP": "escape loop %1",
    "PM_CONTROL_FROMTO": "for %1 of %2 to %3 %4",
    "PM_CONTROL_FROMTO_INDEX": "index",
    "PM_CONTROL_IFELSEREPORTER": "if %1 then %2 else %3",
    "PM_CONTROL_IFEXPANDABLE_IF": "if",
    "PM_CONTROL_IFEXPANDABLE_THEN": "then",
    "PM_CONTROL_IFEXPANDABLE_ELSE": "else",
    "PM_CONTROL_INLINESTACKOUTPUT": "inline block",
    "PM_CONTROL_ISCLONE": "is clone?",
    "PM_CONTROL_REPEATFORSECONDS": "repeat for %1 seconds",
    "PM_CONTROL_RESTARTPROJECT": "restart project",
    "PM_CONTROL_RUNAS": "as %1 do",
    "PM_CONTROL_RUNFLAG": "run %1",
    "PM_CONTROL_RUNWITHOUTSCREENREFRESH": "run without screen refresh %1",
    "PM_CONTROL_SETCOUNTER": "set counter to %1",
    "PM_CONTROL_STOPSPRITE": "stop %1",
    "PM_CONTROL_STOP_THREAD": "this thread",
    "PM_CONTROL_TRYCATCH_1": "try to do",
    "PM_CONTROL_TRYCATCH_2": "if a block errors %1",
    "PM_CONTROL_TRYCATCH_ERROR": "error",
    "PM_CONTROL_THROWERROR": "throw error %1",
    "PM_CONTROL_WAITORUNTIL": "wait %1 seconds or until %2",
    "PM_CONTROL_WAITUNTILTICK": "wait until next tick",
    "PM_DATA_SETVARIABLEVISIBLE": "set %1 visibility to %2",
    "PM_DATA_VARIABLEVISIBLE": "is %1 visible?",
    "PM_DATA_AMOUNTINLIST": "amount of %1 in %2",
    "PM_DATA_FILTERLIST": "filter %1 %2 %3 %4 %5",
    "PM_DATA_FOREACH": "for %1 %2 of %3",
    "PM_DATA_FOREACH_INDEX": "for each index: %2 in %1",
    "PM_DATA_FOREACH_VALUE": "for each value: %2 in %1",
    "PM_DATA_ITEMEXISTSLIST": "item %1 exists in %2?",
    "PM_DATA_LISTARRAY_GET": "get list %1 as an array",
    "PM_DATA_LISTARRAY_SET": "set %2 to array %1",
    "PM_DATA_LISTEMPTY": "is %1 empty?",
    "PM_DATA_REVERSELIST": "reverse %1",
    "PM_DATA_SHIFTLIST": "shift %1 by %2",
    "PM_DATA_UPVAR_INDEX": "index",
    "PM_DATA_UPVAR_ITEM": "item",
    "PM_EVENT_ALWAYS": "always",
    "PM_EVENT_WHEN": "when %1",
    "PM_EVENT_WHENKEYHIT": "when %1 key hit",
    "PM_EVENT_WHENMOUSESCROLLED": "when mouse scrolled %1",
    "PM_EVENT_WHENMOUSESCROLLED_UP": "up",
    "PM_EVENT_WHENMOUSESCROLLED_DOWN": "down",
    "PM_LOOKS_BLENDMODE": "set blend mode to %1",
    "PM_LOOKS_BLENDMODE_ADDITIVE": "additive",
    "PM_LOOKS_BLENDMODE_DIFFERENCE": "difference",
    "PM_LOOKS_BLENDMODE_MULTIPLICATIVE": "multiplicative",
    "PM_LOOKS_BLENDMODE_NORMAL": "normal",
    "PM_LOOKS_BLENDMODE_SCREEN": "screen",
    "PM_LOOKS_BLENDMODE_SUBTRACTIVE": "subtractive",
    "PM_LOOKS_BUBBLEHEIGHT": "bubble height",
    "PM_LOOKS_BUBBLEWIDTH": "bubble width",
    "PM_LOOKS_CHANGESTRETCH": "change stretch by x: %1 y: %2",
    "PM_LOOKS_CHANGEVISIBILITYOFSPRITEHIDE": "hide %1",
    "PM_LOOKS_CHANGEVISIBILITYOFSPRITESHOW": "show %1",
    "PM_LOOKS_EFFECT_SATURATION": "saturation",
    "PM_LOOKS_EFFECT_RED": "red",
    "PM_LOOKS_EFFECT_GREEN": "green",
    "PM_LOOKS_EFFECT_BLUE": "blue",
    "PM_LOOKS_EFFECT_OPAQUE": "opaque",
    "PM_LOOKS_EFFECT_HORIZ_SHEAR": "horizontal shear",
    "PM_LOOKS_EFFECT_VERTI_SHEAR": "vertical shear",
    "PM_LOOKS_EFFECT_REPEAT_X": "repeat x",
    "PM_LOOKS_EFFECT_REPEAT_Y": "repeat y",
    "PM_LOOKS_GET_EFFECT": "%1 effect",
    "PM_LOOKS_GETINPUTOFCOSTUME": "%1 of %2",
    "PM_LOOKS_GETOTHERSPRITEVISIBLE": "is %1 visible?",
    "PM_LOOKS_GOTARGETLAYER": "go %1 %2",
    "PM_LOOKS_HIDEALLSPRITES": "hide all sprites",
    "PM_LOOKS_LAYERSGETLAYER": "layer",
    "PM_LOOKS_LAYERSSETLAYER": "go to layer %1",
    "PM_LOOKS_PREVIOUSBACKDROP": "previous backdrop",
    "PM_LOOKS_PREVIOUSCOSTUME": "previous costume",
    "PM_LOOKS_SETCOLOR": "set %1 color to %2",
    "PM_LOOKS_SETCOLOR_BORDER": "border",
    "PM_LOOKS_SETCOLOR_FILL": "background",
    "PM_LOOKS_SETCOLOR_TEXT": "text",
    "PM_LOOKS_SETFONT": "set font to %1 with size %2",
    "PM_LOOKS_SETSHAPE": "set text bubble %1 to %2",
    "PM_LOOKS_SETSHAPE_BORDERWIDTH": "border width",
    "PM_LOOKS_SETSHAPE_CORNERRADIUS": "corner radius",
    "PM_LOOKS_SETSHAPE_FONTHEIGHTRATIO": "font height ratio",
    "PM_LOOKS_SETSHAPE_MAXWIDTH": "maximum width",
    "PM_LOOKS_SETSHAPE_MINWIDTH": "minimum width",
    "PM_LOOKS_SETSHAPE_PADDING": "padding size",
    "PM_LOOKS_SETSHAPE_TAILHEIGHT": "tail height",
    "PM_LOOKS_SETSHAPE_LINEHEIGHT": "line height",
    "PM_LOOKS_SETSHAPE_TEXTLIM": "character limit",
    "PM_LOOKS_SETSTRETCH": "set stretch to x: %1 y: %2",
    "PM_LOOKS_SETTINTCOLOR": "set tint color to %1",
    "PM_LOOKS_SETVISIBLE": "set visibility to %1",
    "PM_LOOKS_STOPTALKING": "stop speaking",
    "PM_LOOKS_STRETCHX": "stretch x",
    "PM_LOOKS_STRETCHY": "stretch y",
    "PM_LOOKS_THIS": "this sprite",
    "PM_LOOKS_TINTCOLOR": "tint color",
    "PM_LOOKS_VISIBLE": "visible?",
    "PM_MOTION_CHANGEBYXY": "change by x: %1 y: %2",
    "PM_MOTION_GLIDEDIRECTIONSTEPSINSECONDS": "glide %1 steps %2 in %3 secs",
    "PM_MOTION_GLIDE_BACKWARDS": "backwards",
    "PM_MOTION_GLIDE_DOWN": "down",
    "PM_MOTION_GLIDE_FORWARDS": "forwards",
    "PM_MOTION_GLIDE_UP": "up",
    "PM_MOTION_IFONSPRITEBOUNCE": "if touching %1, bounce",
    "PM_MOTION_IFONSPRITEBOUNCE_EDGE": "mouse-pointer",
    "PM_MOTION_IFONXYBOUNCE": "if touching x: %1 y: %2, bounce",
    "PM_MOTION_MOVEBACKSTEPS": "move back %1 steps",
    "PM_MOTION_MOVEUPDOWNSTEPS": "move %1 %2 steps",
    "PM_MOTION_MOVEUPDOWNSTEPS_UP": "up",
    "PM_MOTION_MOVEUPDOWNSTEPS_DOWN": "down",
    "PM_MOTION_POINTTOWARDS_XY": "point towards x: %1 y: %2",
    "PM_MOTION_POINTINRANDOMDIRECTION": "point in random direction",
    "PM_MOTION_SETROTATIONSTYLE_UPDOWN": "up-down",
    "PM_MOTION_SETROTATIONSTYLE_LOOKAT": "look at",
    "PM_MOTION_TURNRIGHTAROUNDXY": "turn %1 %2 degrees around x: %3 y: %4",
    "PM_MOTION_TURNLEFTAROUNDXY": "turn %1 %2 degrees around x: %3 y: %4",
    "PM_MOTION_TURNAROUND": "turn around",
    "PM_OPERATORS_ADVMATH": "%1 %2 %3",
    "PM_OPERATORS_ADVMATH_LOG": "log",
    "PM_OPERATORS_ADVMATH_ROOT": "root",
    "PM_OPERATORS_AVERAGE": "average",
    "PM_OPERATORS_CASE_LOWER": "lowercase",
    "PM_OPERATORS_CASE_TO": "%1 to %2",
    "PM_OPERATORS_CASE_UPPER": "uppercase",
    "PM_OPERATORS_CHARACTER_TO_CODE": "character %1 to id",
    "PM_OPERATORS_CODE_TO_CHARACTER": "id %1 to character",
    "PM_OPERATORS_COUNT_APPEAR_TIMES": "amount of times %1 appears in %2",
    "PM_OPERATORS_CONSTRAIN": "constrain %1 min %2 max %3",
    "PM_OPERATORS_CHAR_NEWLINE": "new line",
    "PM_OPERATORS_CHAR_TAB": "tab character",
    "PM_OPERATORS_DECODE": "decode %1 with %2",
    "PM_OPERATORS_ENCODE": "encode %1 with %2",
    "PM_OPERATORS_ENCODING_B16": "base16",
    "PM_OPERATORS_ENCODING_B64": "base64",
    "PM_OPERATORS_ENCODING_URI": "URI component",
    "PM_OPERATORS_EXPANDABLEBOOL_AND": "and",
    "PM_OPERATORS_EXPANDABLEBOOL_OR": "or",
    "PM_OPERATORS_EXPANDABLEBOOL_XOR": "xor",
    "PM_OPERATORS_EXPANDABLEBOOL_NAND": "nand",
    "PM_OPERATORS_EXPANDABLEBOOL_NOR": "nor",
    "PM_OPERATORS_EXPANDABLEBOOL_XNOR": "xnor",
    "PM_OPERATORS_FALSE": "false",
    "PM_OPERATORS_GTE": "%1 ≥ %2",
    "PM_OPERATORS_INDEX_OF_TEXT_IN_TEXT": "index of %1 in %2",
    "PM_OPERATORS_INTERPOLATE": "interpolate %1 to %2 by %3",
    "PM_OPERATORS_JOIN3": "join %1 %2 %3",
    "PM_OPERATORS_JOINE": "join %1",
    "PM_OPERATORS_JOIN_PEAR": "pear",
    "PM_OPERATORS_JOIN_ORANGE": "orange",
    "PM_OPERATORS_JOIN_MANGO": "mango",
    "PM_OPERATORS_JOIN_STRAWBERRY": "strawberry",
    "PM_OPERATORS_JOIN_PINEAPPLE": "pineapple",
    "PM_OPERATORS_JOIN_GRAPE": "grape",
    "PM_OPERATORS_JOIN_KIWI": "kiwi",
    "PM_OPERATORS_LAST_INDEX_OF_TEXT_IN_TEXT": "last index of %1 in %2",
    "PM_OPERATORS_LETTERSFROMTOIN": "letters from %1 to %2 in %3",
    "PM_OPERATORS_LTE": "%1 ≤ %2",
    "PM_OPERATORS_MATHOP_LOG2": "log2",
    "PM_OPERATORS_MATHOP_SIGN": "sign",
    "PM_OPERATORS_MAXIMUM": "maximum",
    "PM_OPERATORS_MINIMUM": "minimum",
    "PM_OPERATORS_NAND": "%1 nand %2",
    "PM_OPERATORS_NOR": "%1 nor %2",
    "PM_OPERATORS_NOTEQUAL": "%1 ≠ %2",
    "PM_OPERATORS_NULL": "null",
    "PM_OPERATORS_POWER": "%1 ^ %2",
    "PM_OPERATORS_RANDOMBOOLEAN": "random",
    "PM_OPERATORS_RANGE": "range",
    "PM_OPERATORS_RANGE_EXPANDABLE": "%1 of %2",
    "PM_OPERATORS_READLINE": "line %1 in %2",
    "PM_OPERATORS_REGEX": "match %1 with regex %2 %3",
    "PM_OPERATORS_REPLACE": "replace all %2 with %3 in %1",
    "PM_OPERATORS_REPLACE_FIRST": "replace first %2 with %3 in %1",
    "PM_OPERATORS_STARTSWITH": "%1 %2 with %3?",
    "PM_OPERATORS_STARTSWITH_STARTS": "starts",
    "PM_OPERATORS_STARTSWITH_ENDS": "ends",
    "PM_OPERATORS_TEXT_INCLUDES_LETTER_FROM": "%1 includes a letter from %2?",
    "PM_OPERATORS_TRUE": "true",
    "PM_OPERATORS_TYPE_BOOLEAN": "boolean",
    "PM_OPERATORS_TYPE_NUMBER": "number",
    "PM_OPERATORS_TYPE_STRING": "string",
    "PM_OPERATORS_VALID_TYPE": "is %1 a valid %2?",
    "PM_OPERATORS_XNOR": "%1 xnor %2",
    "PM_OPERATORS_XOR": "%1 xor %2",
    "PM_PROCEDURES_REEVALUATE": "reevaluate %1",
    "PM_PROCEDURES_SET": "set %1 to %2",
    "PM_SENSING_BROWSER": "browser",
    "PM_SENSING_CLIPBOARD_SET": "set clipboard to %1",
    "PM_SENSING_CLIPBOARD_GET": "clipboard",
    "PM_SENSING_CURRENT_TIMESTAMP": "timestamp",
    "PM_SENSING_DIRECTION_TO_POINTS": "direction from %3 %4 to %1 %2",
    "PM_SENSING_DISTANCE_TO_POINTS": "distance from %1 %2 to %3 %4",
    "PM_SENSING_DRAGGABLE": "draggable?",
    "PM_SENSING_FINGER_DOWN": "finger %1 down?",
    "PM_SENSING_FINGER_TAPPED": "finger %1 tapped?",
    "PM_SENSING_FINGER_X": "finger %1 x",
    "PM_SENSING_FINGER_Y": "finger %1 y",
    "PM_SENSING_GET_SPRITE_WITH_ATTRIB": "get sprite with %1 set to %2",
    "PM_SENSING_HAS_NUMBER": "%1 has number?",
    "PM_SENSING_HAS_TEXT": "%1 has text?",
    "PM_SENSING_IS_NUMBER": "%1 is number?",
    "PM_SENSING_IS_TEXT": "%1 is text?",
    "PM_SENSING_IS_UPPERCASE": "is character %1 uppercase?",
    "PM_SENSING_KEY_HIT": "key %1 hit?",
    "PM_SENSING_LOGGED_IN": "logged in?",
    "PM_SENSING_MOBILE": "mobile?",
    "PM_SENSING_MOUSE_BUTTON_ANY": "any",
    "PM_SENSING_MOUSE_BUTTON_CLICKED": "%1 mouse clicked?",
    "PM_SENSING_MOUSE_BUTTON_DOWN": "%1 mouse down?",
    "PM_SENSING_MOUSE_BUTTON_LEFT": "left",
    "PM_SENSING_MOUSE_BUTTON_MIDDLE": "middle",
    "PM_SENSING_MOUSE_BUTTON_RELEASED": "%1 mouse released?",
    "PM_SENSING_MOUSE_BUTTON_RIGHT": "right",
    "PM_SENSING_MOUSE_CLICKED": "mouse clicked?",
    "PM_SENSING_MOUSE_SCROLLING": "is mouse scrolling %1?",
    "PM_SENSING_OBJECT_TOUCHING_CLONE": "%1 touching clone of %2?",
    "PM_SENSING_OBJECT_TOUCHING_OBJECT": "%1 touching %2?",
    "PM_SENSING_OPERATING_SYSTEM": "operating system",
    "PM_SENSING_REGEX_TEST": "test regex %2 %3 with text %1",
    "PM_SENSING_URL": "url",
    "PM_SENSING_XY_OF_TOUCHING": "%1 of touching %2 point",
    "PM_SOUND_GETEFFECTVALUE": "%1 effect",
    "PM_SOUND_GETLENGTH": "length of %1",
    "PM_SOUND_GETSOUNDVOLUME": "current volume of %1",
    "PM_SOUND_GETTIMEPOSITION": "current time position of %1",
    "PM_SOUND_ISSOUNDPLAYING": "is %1 playing?",
    "PM_SOUND_PAUSE": "pause sound %1",
    "PM_SOUND_PAUSEALLSOUNDS": "pause all sounds",
    "PM_SOUND_PLAYALLSOUNDS": "play all sounds",
    "PM_SOUND_PLAY_AT_SECONDS": "start sound %1 at %2 seconds",
    "PM_SOUND_PLAY_AT_SECONDS_UNTIL_DONE": "play sound %1 starting at %2 seconds until done",
    "PM_SOUND_SET_STOP_FADEOUT_TO": "set fade out to %1 seconds on %2",
    "PM_SOUND_STOP": "stop sound %1",
    "PM_CATEGORY_LISTS": "Lists",
    "PM_CATEGORY_STRINGS": "Strings",
    "PM_MOVE_TO_TOP": "Move to Top",
    "PM_MOVE_TO_BOTTOM": "Move to Bottom",
    "PM_MOVE_BY_CATEGORY": "Organize by Category",
    "PM_PIN": "Pin",
    "PM_UNPIN": "Unpin",
    "PM_UNPIN_ALL": "Unpin All",
    "PM_PROCCODE_USED": "Custom block name is already in use!",
    "PM_PROCEDURE_GLOBAL_LABEL": "Global Blocks",
    "PM_PROCEDURE_PRIVATE_LABEL": "Local Blocks",
    "PM_COLLAPSE_ALL": "Collapse All",
    "PM_COLLAPSE_BLOCK": "Collapse Block",
    "PM_COLLAPSE_X_BLOCKS": "Collapse %1 Blocks",
    "PM_EXPAND_ALL": "Expand All",
    "PM_EXPAND_BLOCK": "Expand Block",
    "PM_EXPAND_X_BLOCKS": "Expand %1 Blocks",
    "PM_INLINE_BLOCK": "Inline Inputs",
    "PM_EXTERNAL_BLOCK": "External Inputs",
    "PM_EXPAND_EXPANDABLE": "Expand",
    "PM_RETRACT_EXPANDABLE": "Retract"
};

Blockly.ScratchMsgs.pmLocales["es-419"] = {
    "PM_CONTROL_CASE": "caso %1 %2",
    "PM_CONTROL_CASE_DEFAULT": "predeterminado",
    "PM_CONTROL_CASE_EXIT": "salir del caso %1",
    "PM_CONTROL_CASE_NEXT": "ejecutar siguiente caso cuando %1",
    "PM_CONTROL_CASE_SWITCH": "opciones %1 %2",
    "PM_CONTROL_CONTINUELOOP": "continuar bucle %1",
    "PM_CONTROL_DECRCOUNTER": "disminuír contador",
    "PM_CONTROL_DELETECLONESOF": "eliminar clones de %1",
    "PM_CONTROL_DO": " hacer %1 %2",
    "PM_CONTROL_ESCAPELOOP": "salir de bucle %1",
    "PM_CONTROL_FROMTO": "por %1 de %2 a %3 %4",
    "PM_CONTROL_FROMTO_INDEX": "índice",
    "PM_CONTROL_IFELSEREPORTER": "si %1 entonces %2 si no %3",
    "PM_CONTROL_IFEXPANDABLE_IF": "si",
    "PM_CONTROL_IFEXPANDABLE_THEN": "entonces",
    "PM_CONTROL_IFEXPANDABLE_ELSE": "si no",
    "PM_CONTROL_INLINESTACKOUTPUT": "bloque embebido",
    "PM_CONTROL_ISCLONE": "¿es clon?",
    "PM_CONTROL_REPEATFORSECONDS": "repetir por %1 segundos",
    "PM_CONTROL_RESTARTPROJECT": "reiniciar proyecto",
    "PM_CONTROL_RUNAS": "como %1 ejecutar",
    "PM_CONTROL_RUNFLAG": "ejecutar %1",
    "PM_CONTROL_RUNWITHOUTSCREENREFRESH": "ejecutar sin refrescar pantalla %1",
    "PM_CONTROL_SETCOUNTER": "establecer contador a %1",
    "PM_CONTROL_STOPSPRITE": "detener %1",
    "PM_CONTROL_STOP_THREAD": "este hilo",
    "PM_CONTROL_TRYCATCH_1": "intentar ejecutar",
    "PM_CONTROL_TRYCATCH_2": "si un bloque falla %1",
    "PM_CONTROL_TRYCATCH_ERROR": "error",
    "PM_CONTROL_THROWERROR": "retornar error %1",
    "PM_CONTROL_WAITORUNTIL": "esperar %1 segundos o hasta que %2",
    "PM_CONTROL_WAITUNTILTICK": "esperar al siguiente tick",
    "PM_DATA_SETVARIABLEVISIBLE": "establecer la visibilidad de %1 a %2",
    "PM_DATA_VARIABLEVISIBLE": "¿es %1 visible?",
    "PM_DATA_AMOUNTINLIST": "cantidad de %1 en %2",
    "PM_DATA_FILTERLIST": "filtrar %1 %2 %3 %4 %5",
    "PM_DATA_FOREACH": "por %1 %2 de %3",
    "PM_DATA_FOREACH_INDEX": "por cada índice: %2 en %1",
    "PM_DATA_FOREACH_VALUE": "por cada valor: %2 en %1",
    "PM_DATA_ITEMEXISTSLIST": "¿item %1 existe en %2?",
    "PM_DATA_LISTARRAY_GET": "retornar lista %1 como array",
    "PM_DATA_LISTARRAY_SET": "establecer %2 a array %1",
    "PM_DATA_LISTEMPTY": "¿%1 está vacío?",
    "PM_DATA_REVERSELIST": "invertir orden de %1",
    "PM_DATA_SHIFTLIST": "mover %1 por %2",
    "PM_DATA_UPVAR_INDEX": "índice",
    "PM_DATA_UPVAR_ITEM": "item",
    "PM_EVENT_ALWAYS": "siempre",
    "PM_EVENT_WHEN": "cuando %1",
    "PM_EVENT_WHENKEYHIT": "cuando la tecla %1 ha sido presionada",
    "PM_EVENT_WHENMOUSESCROLLED": "cuando el mouse se desplaza %1",
    "PM_EVENT_WHENMOUSESCROLLED_UP": "arriba",
    "PM_EVENT_WHENMOUSESCROLLED_DOWN": "abajo",
    "PM_LOOKS_BLENDMODE": "establecer modo de fusión a %1",
    "PM_LOOKS_BLENDMODE_ADDITIVE": "aditivo",
    "PM_LOOKS_BLENDMODE_DIFFERENCE": "diferencia",
    "PM_LOOKS_BLENDMODE_MULTIPLICATIVE": "multiplicativo",
    "PM_LOOKS_BLENDMODE_NORMAL": "normal",
    "PM_LOOKS_BLENDMODE_SCREEN": "pantalla",
    "PM_LOOKS_BLENDMODE_SUBTRACTIVE": "substractivo",
    "PM_LOOKS_BUBBLEHEIGHT": "altura de la burbuja",
    "PM_LOOKS_BUBBLEWIDTH": "anchode la burbuja",
    "PM_LOOKS_CHANGESTRETCH": "cambiar estiramiento por x: %1 y: %2",
    "PM_LOOKS_CHANGEVISIBILITYOFSPRITEHIDE": "esconder %1",
    "PM_LOOKS_CHANGEVISIBILITYOFSPRITESHOW": "mostrar %1",
    "PM_LOOKS_EFFECT_SATURATION": "saturación",
    "PM_LOOKS_EFFECT_RED": "roj",
    "PM_LOOKS_EFFECT_GREEN": "verde",
    "PM_LOOKS_EFFECT_BLUE": "azul",
    "PM_LOOKS_EFFECT_OPAQUE": "opaco",
    "PM_LOOKS_EFFECT_HORIZ_SHEAR": "corte horizontal",
    "PM_LOOKS_EFFECT_VERTI_SHEAR": "corte vertical",
    "PM_LOOKS_EFFECT_REPEAT_X": "repetir x",
    "PM_LOOKS_EFFECT_REPEAT_Y": "repetir y",
    "PM_LOOKS_GET_EFFECT": "valor de efecto %1",
    "PM_LOOKS_GETINPUTOFCOSTUME": "%1 de %2",
    "PM_LOOKS_GETOTHERSPRITEVISIBLE": "¿es %1 visible?",
    "PM_LOOKS_GOTARGETLAYER": "ir %1 %2",
    "PM_LOOKS_HIDEALLSPRITES": "esconder todos los sprites",
    "PM_LOOKS_LAYERSGETLAYER": "capa",
    "PM_LOOKS_LAYERSSETLAYER": "ir a capa %1",
    "PM_LOOKS_PREVIOUSBACKDROP": "fondo anterior",
    "PM_LOOKS_PREVIOUSCOSTUME": "disfraz anterior",
    "PM_LOOKS_SETCOLOR": "establecer color de %1 a %2",
    "PM_LOOKS_SETCOLOR_BORDER": "borde",
    "PM_LOOKS_SETCOLOR_FILL": "fondo",
    "PM_LOOKS_SETCOLOR_TEXT": "texto",
    "PM_LOOKS_SETFONT": "establecer fuente a %1 con tamaño %2",
    "PM_LOOKS_SETSHAPE": "establecer %1 de la burbuja a %2",
    "PM_LOOKS_SETSHAPE_BORDERWIDTH": "ancho del borde",
    "PM_LOOKS_SETSHAPE_CORNERRADIUS": "radio de las esquinas",
    "PM_LOOKS_SETSHAPE_FONTHEIGHTRATIO": "relación del tamaño de fuente",
    "PM_LOOKS_SETSHAPE_MAXWIDTH": "ancho máximo",
    "PM_LOOKS_SETSHAPE_MINWIDTH": "ancho mínimo",
    "PM_LOOKS_SETSHAPE_PADDING": "tamaño de relleno",
    "PM_LOOKS_SETSHAPE_TAILHEIGHT": "alto de la cola",
    "PM_LOOKS_SETSHAPE_LINEHEIGHT": "alto de las líneas",
    "PM_LOOKS_SETSHAPE_TEXTLIM": "límite de caracteres",
    "PM_LOOKS_SETSTRETCH": "establecer estiramiento a x: %1 y: %2",
    "PM_LOOKS_SETTINTCOLOR": "establecer color de tinta a %1",
    "PM_LOOKS_SETVISIBLE": "establecer visibilidad a %1",
    "PM_LOOKS_STOPTALKING": "dejar de hablar",
    "PM_LOOKS_STRETCHX": "x de estiramiento",
    "PM_LOOKS_STRETCHY": "y de estiramiento",
    "PM_LOOKS_THIS": "este sprite",
    "PM_LOOKS_TINTCOLOR": "color de tinta",
    "PM_LOOKS_VISIBLE": "¿visible?",
    "PM_MOTION_CHANGEBYXY": "cambiar por x: %1 y: %2",
    "PM_MOTION_GLIDEDIRECTIONSTEPSINSECONDS": "deslizar por %1 pasos hacia %2 en %3 segundos",
    "PM_MOTION_GLIDE_BACKWARDS": "atrás",
    "PM_MOTION_GLIDE_DOWN": "abajo",
    "PM_MOTION_GLIDE_FORWARDS": "adelante",
    "PM_MOTION_GLIDE_UP": "arriba",
    "PM_MOTION_IFONSPRITEBOUNCE": "si toca %1, rebotar",
    "PM_MOTION_IFONSPRITEBOUNCE_EDGE": "puntero del mouse",
    "PM_MOTION_IFONXYBOUNCE": "si toca x: %1 y: %2, rebotar",
    "PM_MOTION_MOVEBACKSTEPS": "mover %1 pasos hacia atrás",
    "PM_MOTION_MOVEUPDOWNSTEPS": "mover %1 pasos hacia %2",
    "PM_MOTION_MOVEUPDOWNSTEPS_UP": "arriba",
    "PM_MOTION_MOVEUPDOWNSTEPS_DOWN": "abajo",
    "PM_MOTION_POINTTOWARDS_XY": "apuntar hacia x: %1 y: %2",
    "PM_MOTION_POINTINRANDOMDIRECTION": "apuntar aleatoriamente",
    "PM_MOTION_SETROTATIONSTYLE_UPDOWN": "arriba-abajo",
    "PM_MOTION_SETROTATIONSTYLE_LOOKAT": "mirar hacia",
    "PM_MOTION_TURNRIGHTAROUNDXY": "girar %1 %2 grados alrededor de x: %3 y: %4",
    "PM_MOTION_TURNLEFTAROUNDXY": "girar %1 %2 grados alrededor de x: %3 y: %4",
    "PM_MOTION_TURNAROUND": "darse vuelta",
    "PM_OPERATORS_ADVMATH": "%1 %2 %3",
    "PM_OPERATORS_ADVMATH_LOG": "logaritmo",
    "PM_OPERATORS_ADVMATH_ROOT": "raíz",
    "PM_OPERATORS_AVERAGE": "promedio",
    "PM_OPERATORS_CASE_LOWER": "minúscula",
    "PM_OPERATORS_CASE_TO": "%1 a %2",
    "PM_OPERATORS_CASE_UPPER": "mayúscula",
    "PM_OPERATORS_CHARACTER_TO_CODE": "caracter %1 a id",
    "PM_OPERATORS_CODE_TO_CHARACTER": "id %1 a caracter",
    "PM_OPERATORS_COUNT_APPEAR_TIMES": "cantidad de veces que %1 aparece en %2",
    "PM_OPERATORS_CONSTRAIN": "restringir %1 min %2 max %3",
    "PM_OPERATORS_CHAR_NEWLINE": "nueva línea",
    "PM_OPERATORS_CHAR_TAB": "tabulación",
    "PM_OPERATORS_DECODE": "decodificar %1 con %2",
    "PM_OPERATORS_ENCODE": "encodificar %1 con %2",
    "PM_OPERATORS_ENCODING_B16": "base16",
    "PM_OPERATORS_ENCODING_B64": "base64",
    "PM_OPERATORS_ENCODING_URI": "componente URI",
    "PM_OPERATORS_EXPANDABLEBOOL_AND": "and",
    "PM_OPERATORS_EXPANDABLEBOOL_OR": "or",
    "PM_OPERATORS_EXPANDABLEBOOL_XOR": "xor",
    "PM_OPERATORS_EXPANDABLEBOOL_NAND": "nand",
    "PM_OPERATORS_EXPANDABLEBOOL_NOR": "nor",
    "PM_OPERATORS_EXPANDABLEBOOL_XNOR": "xnor",
    "PM_OPERATORS_FALSE": "false",
    "PM_OPERATORS_GTE": "%1 ≥ %2",
    "PM_OPERATORS_INDEX_OF_TEXT_IN_TEXT": "index of %1 in %2",
    "PM_OPERATORS_INTERPOLATE": "interpolate %1 to %2 by %3",
    "PM_OPERATORS_JOIN3": "join %1 %2 %3",
    "PM_OPERATORS_JOINE": "join %1",
    "PM_OPERATORS_JOIN_PEAR": "pear",
    "PM_OPERATORS_JOIN_ORANGE": "orange",
    "PM_OPERATORS_JOIN_MANGO": "mango",
    "PM_OPERATORS_JOIN_STRAWBERRY": "strawberry",
    "PM_OPERATORS_JOIN_PINEAPPLE": "pineapple",
    "PM_OPERATORS_JOIN_GRAPE": "grape",
    "PM_OPERATORS_JOIN_KIWI": "kiwi",
    "PM_OPERATORS_LAST_INDEX_OF_TEXT_IN_TEXT": "last index of %1 in %2",
    "PM_OPERATORS_LETTERSFROMTOIN": "letters from %1 to %2 in %3",
    "PM_OPERATORS_LTE": "%1 ≤ %2",
    "PM_OPERATORS_MATHOP_LOG2": "log2",
    "PM_OPERATORS_MATHOP_SIGN": "sign",
    "PM_OPERATORS_MAXIMUM": "maximum",
    "PM_OPERATORS_MINIMUM": "minimum",
    "PM_OPERATORS_NAND": "%1 nand %2",
    "PM_OPERATORS_NOR": "%1 nor %2",
    "PM_OPERATORS_NOTEQUAL": "%1 ≠ %2",
    "PM_OPERATORS_NULL": "null",
    "PM_OPERATORS_POWER": "%1 ^ %2",
    "PM_OPERATORS_RANDOMBOOLEAN": "random",
    "PM_OPERATORS_RANGE": "range",
    "PM_OPERATORS_RANGE_EXPANDABLE": "%1 of %2",
    "PM_OPERATORS_READLINE": "line %1 in %2",
    "PM_OPERATORS_REGEX": "match %1 with regex %2 %3",
    "PM_OPERATORS_REPLACE": "replace all %2 with %3 in %1",
    "PM_OPERATORS_REPLACE_FIRST": "replace first %2 with %3 in %1",
    "PM_OPERATORS_STARTSWITH": "%1 %2 with %3?",
    "PM_OPERATORS_STARTSWITH_STARTS": "starts",
    "PM_OPERATORS_STARTSWITH_ENDS": "ends",
    "PM_OPERATORS_TEXT_INCLUDES_LETTER_FROM": "%1 includes a letter from %2?",
    "PM_OPERATORS_TRUE": "true",
    "PM_OPERATORS_TYPE_BOOLEAN": "boolean",
    "PM_OPERATORS_TYPE_NUMBER": "number",
    "PM_OPERATORS_TYPE_STRING": "string",
    "PM_OPERATORS_VALID_TYPE": "is %1 a valid %2?",
    "PM_OPERATORS_XNOR": "%1 xnor %2",
    "PM_OPERATORS_XOR": "%1 xor %2",
    "PM_PROCEDURES_REEVALUATE": "reevaluate %1",
    "PM_PROCEDURES_SET": "set %1 to %2",
    "PM_SENSING_BROWSER": "browser",
    "PM_SENSING_CLIPBOARD_SET": "set clipboard to %1",
    "PM_SENSING_CLIPBOARD_GET": "clipboard",
    "PM_SENSING_CURRENT_TIMESTAMP": "timestamp",
    "PM_SENSING_DIRECTION_TO_POINTS": "direction from %3 %4 to %1 %2",
    "PM_SENSING_DISTANCE_TO_POINTS": "distance from %1 %2 to %3 %4",
    "PM_SENSING_DRAGGABLE": "draggable?",
    "PM_SENSING_FINGER_DOWN": "finger %1 down?",
    "PM_SENSING_FINGER_TAPPED": "finger %1 tapped?",
    "PM_SENSING_FINGER_X": "finger %1 x",
    "PM_SENSING_FINGER_Y": "finger %1 y",
    "PM_SENSING_GET_SPRITE_WITH_ATTRIB": "get sprite with %1 set to %2",
    "PM_SENSING_HAS_NUMBER": "%1 has number?",
    "PM_SENSING_HAS_TEXT": "%1 has text?",
    "PM_SENSING_IS_NUMBER": "%1 is number?",
    "PM_SENSING_IS_TEXT": "%1 is text?",
    "PM_SENSING_IS_UPPERCASE": "is character %1 uppercase?",
    "PM_SENSING_KEY_HIT": "key %1 hit?",
    "PM_SENSING_LOGGED_IN": "logged in?",
    "PM_SENSING_MOBILE": "mobile?",
    "PM_SENSING_MOUSE_BUTTON_ANY": "any",
    "PM_SENSING_MOUSE_BUTTON_CLICKED": "%1 mouse clicked?",
    "PM_SENSING_MOUSE_BUTTON_DOWN": "%1 mouse down?",
    "PM_SENSING_MOUSE_BUTTON_LEFT": "left",
    "PM_SENSING_MOUSE_BUTTON_MIDDLE": "middle",
    "PM_SENSING_MOUSE_BUTTON_RELEASED": "%1 mouse released?",
    "PM_SENSING_MOUSE_BUTTON_RIGHT": "right",
    "PM_SENSING_MOUSE_CLICKED": "mouse clicked?",
    "PM_SENSING_MOUSE_SCROLLING": "is mouse scrolling %1?",
    "PM_SENSING_OBJECT_TOUCHING_CLONE": "%1 touching clone of %2?",
    "PM_SENSING_OBJECT_TOUCHING_OBJECT": "%1 touching %2?",
    "PM_SENSING_OPERATING_SYSTEM": "operating system",
    "PM_SENSING_REGEX_TEST": "test regex %2 %3 with text %1",
    "PM_SENSING_URL": "url",
    "PM_SENSING_XY_OF_TOUCHING": "%1 of touching %2 point",
    "PM_SOUND_GETEFFECTVALUE": "%1 effect",
    "PM_SOUND_GETLENGTH": "length of %1",
    "PM_SOUND_GETSOUNDVOLUME": "current volume of %1",
    "PM_SOUND_GETTIMEPOSITION": "current time position of %1",
    "PM_SOUND_ISSOUNDPLAYING": "is %1 playing?",
    "PM_SOUND_PAUSE": "pause sound %1",
    "PM_SOUND_PAUSEALLSOUNDS": "pause all sounds",
    "PM_SOUND_PLAYALLSOUNDS": "play all sounds",
    "PM_SOUND_PLAY_AT_SECONDS": "start sound %1 at %2 seconds",
    "PM_SOUND_PLAY_AT_SECONDS_UNTIL_DONE": "play sound %1 starting at %2 seconds until done",
    "PM_SOUND_SET_STOP_FADEOUT_TO": "set fade out to %1 seconds on %2",
    "PM_SOUND_STOP": "stop sound %1",
    "PM_CATEGORY_LISTS": "Lists",
    "PM_CATEGORY_STRINGS": "Strings",
    "PM_MOVE_TO_TOP": "Move to Top",
    "PM_MOVE_TO_BOTTOM": "Move to Bottom",
    "PM_MOVE_BY_CATEGORY": "Organize by Category",
    "PM_PIN": "Pin",
    "PM_UNPIN": "Unpin",
    "PM_UNPIN_ALL": "Unpin All",
    "PM_PROCCODE_USED": "Custom block name is already in use!",
    "PM_PROCEDURE_GLOBAL_LABEL": "Global Blocks",
    "PM_PROCEDURE_PRIVATE_LABEL": "Local Blocks",
    "PM_COLLAPSE_ALL": "Collapse All",
    "PM_COLLAPSE_BLOCK": "Collapse Block",
    "PM_COLLAPSE_X_BLOCKS": "Collapse %1 Blocks",
    "PM_EXPAND_ALL": "Expand All",
    "PM_EXPAND_BLOCK": "Expand Block",
    "PM_EXPAND_X_BLOCKS": "Expand %1 Blocks",
    "PM_INLINE_BLOCK": "Inline Inputs",
    "PM_EXTERNAL_BLOCK": "External Inputs",
    "PM_EXPAND_EXPANDABLE": "Expand",
    "PM_RETRACT_EXPANDABLE": "Retract"
};
